In [1]:
import pandas as pd
import requests
import os

In [2]:
from dotenv import load_dotenv

In [3]:
load_dotenv()

True

In [7]:
RAPID_API_KEY = os.getenv("RAPID_API_KEY")
RAPID_API_KEY

'd13b909ab9msh1a2c3a1f2d58371p1b46cejsnbdfbd19430dd'

In [10]:
url = "https://weatherbit-v1-mashape.p.rapidapi.com/forecast/3hourly"

querystring = {"lat":"28","lon":"84","units":"metric","lang":"en"}

headers = {
	"x-rapidapi-key": RAPID_API_KEY,
	"x-rapidapi-host": "weatherbit-v1-mashape.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

response.json()

{'city_name': 'Bhattarai Danda',
 'country_code': 'NP',
 'data': [{'app_temp': 16.4,
   'clouds': 0,
   'clouds_hi': 0,
   'clouds_low': 58,
   'clouds_mid': 43,
   'datetime': '2026-01-02:10',
   'dewpt': 10.1,
   'dhi': 74,
   'dni': 672,
   'ghi': 271,
   'ozone': 259,
   'pod': 'd',
   'pop': 0,
   'precip': 0,
   'pres': 919,
   'rh': 66,
   'slp': 1016,
   'snow': 0,
   'snow_depth': 0,
   'solar_rad': 262.90912,
   'temp': 16.4,
   'timestamp_local': '2026-01-02T15:45:00',
   'timestamp_utc': '2026-01-02T10:00:00',
   'ts': 1767348000,
   'uv': 2,
   'vis': 19.8,
   'weather': {'icon': 'c01d', 'code': 800, 'description': 'Clear Sky'},
   'wind_cdir': 'SSE',
   'wind_cdir_full': 'south-southeast',
   'wind_dir': 151,
   'wind_gust_spd': 4.36,
   'wind_spd': 2.23},
  {'app_temp': 15.4,
   'clouds': 0,
   'clouds_hi': 0,
   'clouds_low': 43,
   'clouds_mid': 31,
   'datetime': '2026-01-02:11',
   'dewpt': 10.1,
   'dhi': 43,
   'dni': 398,
   'ghi': 82,
   'ozone': 258,
   'pod': 'd',
   'pop': 0,
   'precip': 0,
   'pres': 919,
   'rh': 71,
   'slp': 1016,
   'snow': 0,
   'snow_depth': 0,
   'solar_rad': 79.06807,
   'temp': 15.4,
   'timestamp_local': '2026-01-02T16:45:00',
   'timestamp_utc': '2026-01-02T11:00:00',
   'ts': 1767351600,
   'uv': 2,
   'vis': 21.3,
   'weather': {'icon': 'c01d', 'code': 800, 'description': 'Clear Sky'},
   'wind_cdir': 'SSE',
   'wind_cdir_full': 'south-southeast',
   'wind_dir': 155,
   'wind_gust_spd': 4.19,
   'wind_spd': 1.43},
  {'app_temp': 13.7,
   'clouds': 0,
   'clouds_hi': 0,
   'clouds_low': 30,
   'clouds_mid': 26,
   'datetime': '2026-01-02:12',
   'dewpt': 10.3,
   'dhi': 0,
   'dni': 0,
   'ghi': 0,
   'ozone': 256,
   'pod': 'n',
   'pop': 0,
   'precip': 0,
   'pres': 919,
   'rh': 80,
   'slp': 1016,
   'snow': 0,
   'snow_depth': 0,
   'solar_rad': 0,
   'temp': 13.7,
   'timestamp_local': '2026-01-02T17:45:00',
   'timestamp_utc': '2026-01-02T12:00:00',
   'ts': 1767355200,
   'uv': 0,
   'vis': 24,
   'weather': {'icon': 'c01n', 'code': 800, 'description': 'Clear Sky'},
   'wind_cdir': 'SSE',
   'wind_cdir_full': 'south-southeast',
   'wind_dir': 153,
   'wind_gust_spd': 2.62,
   'wind_spd': 0.9},
  {'app_temp': 12.1,
   'clouds': 0,
   'clouds_hi': 0,
   'clouds_low': 37,
   'clouds_mid': 3,
   'datetime': '2026-01-02:13',
   'dewpt': 10,
   'dhi': 0,
   'dni': 0,
   'ghi': 0,
   'ozone': 256,
   'pod': 'n',
   'pop': 0,
   'precip': 0,
   'pres': 919,
   'rh': 87,
   'slp': 1017,
   'snow': 0,
   'snow_depth': 0,
   'solar_rad': 0,
   'temp': 12.1,
   'timestamp_local': '2026-01-02T18:45:00',
   'timestamp_utc': '2026-01-02T13:00:00',
   'ts': 1767358800,
   'uv': 0,
   'vis': 20.7,
   'weather': {'icon': 'c01n', 'code': 800, 'description': 'Clear Sky'},
   'wind_cdir': 'SSE',
   'wind_cdir_full': 'south-southeast',
   'wind_dir': 166,
   'wind_gust_spd': 1.57,
   'wind_spd': 0.48},
  {'app_temp': 11.4,
   'clouds': 0,
   'clouds_hi': 0,
   'clouds_low': 24,
   'clouds_mid': 0,
   'datetime': '2026-01-02:14',
   'dewpt': 9.7,
   'dhi': 0,
   'dni': 0,
   'ghi': 0,
   'ozone': 255,
   'pod': 'n',
   'pop': 0,
   'precip': 0,
   'pres': 920,
   'rh': 89,
   'slp': 1018,
   'snow': 0,
   'snow_depth': 0,
   'solar_rad': 0,
   'temp': 11.4,
   'timestamp_local': '2026-01-02T19:45:00',
   'timestamp_utc': '2026-01-02T14:00:00',
   'ts': 1767362400,
   'uv': 0,
   'vis': 24,
   'weather': {'icon': 'c01n', 'code': 800, 'description': 'Clear Sky'},
   'wind_cdir': 'W',
   'wind_cdir_full': 'west',
   'wind_dir': 272,
   'wind_gust_spd': 0.89,
   'wind_spd': 0.65},
  {'app_temp': 9.9,
   'clouds': 0,
   'clouds_hi': 0,
   'clouds_low': 0,
   'clouds_mid': 0,
   'datetime': '2026-01-02:15',
   'dewpt': 8.8,
   'dhi': 0,
   'dni': 0,
   'ghi': 0,
   'ozone': 256,
   'pod': 'n',
   'pop': 0,
   'precip': 0,
   'pres': 920,
   'rh': 93,
   'slp': 1019,
   'snow': 0,
   'snow_depth': 0,
   'solar_rad': 0,
   'temp': 9.9,
   'timestamp_local': '2026-01-02T20:45:00',
   'timestamp_utc': '2026-01-02T15:00:00',
   'ts': 1767366000,
   'uv': 0,
   'vis': 24,
   'weather': {'icon': 'c01n', 'code': 800, 'description': 'Clear Sky'},
   'wind_cdir': 'WNW',
   'wind_cdir_full': 'west-northwest',
   'wind_dir': 301,
   'wind_gust_spd': 2.06,
   'wind_spd': 1.26},
  {'app_temp': 8.9,
   'clouds': 0,
   'clouds_hi': 0,
   'clouds_low': 36,
   'clouds_mid': 0,
   'datetime': '2026-01-02:16',
   'dewpt': 8.2,
   'dhi': 0,
   'dni': 0,
   'ghi': 0,
   'ozone': 257,
   'pod': 'n',
   'pop': 0,
   'precip': 0,
   'pres': 920,
   'rh': 95,
   'slp': 1019,
   'snow': 0,
   'snow_depth': 0,
   'solar_rad': 0,
   'temp': 8.9,
   'timestamp_local': '2026-01-02T21:45:00',
   'timestamp_utc': '2026-01-02T16:00:00',
   'ts': 1767369600,
   'uv': 0,
   'vis': 24,
   'weather': {'icon': 'c01n', 'code': 800, 'description': 'Clear Sky'},
   'wind_cdir': 'NW',
   'wind_cdir_full': 'northwest',
   'wind_dir': 316,
   'wind_gust_spd': 2.6,
   'wind_spd': 1.52},
  {'app_temp': 8.5,
   'clouds': 0,
   'clouds_hi': 0,
   'clouds_low': 33,
   'clouds_mid': 0,
   'datetime': '2026-01-02:17',
   'dewpt': 7.6,
   'dhi': 0,
   'dni': 0,
   'ghi': 0,
   'ozone': 257,
   'pod': 'n',
   'pop': 0,
   'precip': 0,
   'pres': 920,
   'rh': 94,
   'slp': 1019,
   'snow': 0,
   'snow_depth': 0,
   'solar_rad': 0,
   'temp': 8.5,
   'timestamp_local': '2026-01-02T22:45:00',
   'timestamp_utc': '2026-01-02T17:00:00',
   'ts': 1767373200,
   'uv': 0,
   'vis': 24,
   'weather': {'icon': 'c01n', 'code': 800, 'description': 'Clear Sky'},
   'wind_cdir': 'NW',
   'wind_cdir_full': 'northwest',
   'wind_dir': 317,
   'wind_gust_spd': 2.58,
   'wind_spd': 1.5},
  {'app_temp': 8.1,
   'clouds': 0,
   'clouds_hi': 0,
   'clouds_low': 31,
   'clouds_mid': 0,
   'datetime': '2026-01-02:18',
   'dewpt': 7.2,
   'dhi': 0,
   'dni': 0,
   'ghi': 0,
   'ozone': 255,
   'pod': 'n',
   'pop': 0,
   'precip': 0,
   'pres': 919,
   'rh': 94,
   'slp': 1018,
   'snow': 0,
   'snow_depth': 0,
   'solar_rad': 0,
   'temp': 8.1,
   'timestamp_local': '2026-01-02T23:45:00',
   'timestamp_utc': '2026-01-02T18:00:00',
   'ts': 1767376800,
   'uv': 0,
   'vis': 24,
   'weather': {'icon': 'c01n', 'code': 800, 'description': 'Clear Sky'},
   'wind_cdir': 'NW',
   'wind_cdir_full': 'northwest',
   'wind_dir': 317,
   'wind_gust_spd': 2.62,
   'wind_spd': 1.54},
  {'app_temp': 7.9,
   'clouds': 0,
   'clouds_hi': 0,
   'clouds_low': 23,
   'clouds_mid': 0,
   'datetime': '2026-01-02:19',
   'dewpt': 6.8,
   'dhi': 0,
   'dni': 0,
   'ghi': 0,
   'ozone': 255,
   'pod': 'n',
   'pop': 0,
   'precip': 0,
   'pres': 919,
   'rh': 93,
   'slp': 1018,
   'snow': 0,
   'snow_depth': 0,
   'solar_rad': 0,
   'temp': 7.9,
   'timestamp_local': '2026-01-03T00:45:00',
   'timestamp_utc': '2026-01-02T19:00:00',
   'ts': 1767380400,
   'uv': 0,
   'vis': 24,
   'weather': {'icon': 'c01n', 'code': 800, 'description': 'Clear Sky'},
   'wind_cdir': 'NW',
   'wind_cdir_full': 'northwest',
   'wind_dir': 325,
   'wind_gust_spd': 2.62,
   'wind_spd': 1.47},
  {'app_temp': 7.6,
   'clouds': 0,
   'clouds_hi': 0,
   'clouds_low': 22,
   'clouds_mid': 0,
   'datetime': '2026-01-02:20',
   'dewpt': 6.5,
   'dhi': 0,
   'dni': 0,
   'ghi': 0,
   'ozone': 254,
   'pod': 'n',
   'pop': 0,
   'precip': 0,
   'pres': 919,
   'rh': 93,
   'slp': 1018,
   'snow': 0,
   'snow_depth': 0,
   'solar_rad': 0,
   'temp': 7.6,
   'timestamp_local': '2026-01-03T01:45:00',
   'timestamp_utc': '2026-01-02T20:00:00',
   'ts': 1767384000,
   'uv': 0,
   'vis': 24,
   'weather': {'icon': 'c01n', 'code': 800, 'description': 'Clear Sky'},
   'wind_cdir': 'NW',
   'wind_cdir_full': 'northwest',
   'wind_dir': 322,
   'wind_gust_spd': 2.57,
   'wind_spd': 1.51},
  {'app_temp': 7.3,
   'clouds': 0,
   'clouds_hi': 0,
   'clouds_low': 17,
   'clouds_mid': 0,
   'datetime': '2026-01-02:21',
   'dewpt': 6.2,
   'dhi': 0,
   'dni': 0,
   'ghi': 0,
   'ozone': 255,
   'pod': 'n',
   'pop': 0,
   'precip': 0,
   'pres': 918,
   'rh': 93,
   'slp': 1018,
   'snow': 0,
   'snow_depth': 0,
   'solar_rad': 0,
   'temp': 7.3,
   'timestamp_local': '2026-01-03T02:45:00',
   'timestamp_utc': '2026-01-02T21:00:00',
   'ts': 1767387600,
   'uv': 0,
   'vis': 24,
   'weather': {'icon': 'c01n', 'code': 800, 'description': 'Clear Sky'},
   'wind_cdir': 'NW',
   'wind_cdir_full': 'northwest',
   'wind_dir': 318,
   'wind_gust_spd': 2.57,
   'wind_spd': 1.5},
  {'app_temp': 6.1,
   'clouds': 0,
   'clouds_hi': 0,
   'clouds_low': 26,
   'clouds_mid': 0,
   'datetime': '2026-01-02:22',
   'dewpt': 5.9,
   'dhi': 0,
   'dni': 0,
   'ghi': 0,
   'ozone': 255,
   'pod': 'n',
   'pop': 0,
   'precip': 0,
   'pres': 918,
   'rh': 93,
   'slp': 1018,
   'snow': 0,
   'snow_depth': 0,
   'solar_rad': 0,
   'temp': 6.9,
   'timestamp_local': '2026-01-03T03:45:00',
   'timestamp_utc': '2026-01-02T22:00:00',
   'ts': 1767391200,
   'uv': 0,
   'vis': 24,
   'weather': {'icon': 'c01n', 'code': 800, 'description': 'Clear Sky'},
   'wind_cdir': 'NW',
   'wind_cdir_full': 'northwest',
   'wind_dir': 315,
   'wind_gust_spd': 2.7,
   'wind_spd': 1.58},
  {'app_temp': 5.9,
   'clouds': 0,
   'clouds_hi': 0,
   'clouds_low': 27,
   'clouds_mid': 0,
   'datetime': '2026-01-02:23',
   'dewpt': 5.8,
   'dhi': 0,
   'dni': 0,
   'ghi': 0,
   'ozone': 257,
   'pod': 'n',
   'pop': 0,
   'precip': 0,
   'pres': 918,
   'rh': 93,
   'slp': 1018,
   'snow': 0,
   'snow_depth': 0,
   'solar_rad': 0,
   'temp': 6.8,
   'timestamp_local': '2026-01-03T04:45:00',
   'timestamp_utc': '2026-01-02T23:00:00',
   'ts': 1767394800,
   'uv': 0,
   'vis': 24,
   'weather': {'icon': 'c01n', 'code': 800, 'description': 'Clear Sky'},
   'wind_cdir': 'NW',
   'wind_cdir_full': 'northwest',
   'wind_dir': 320,
   'wind_gust_spd': 2.74,
   'wind_spd': 1.58},
  {'app_temp': 5.6,
   'clouds': 0,
   'clouds_hi': 0,
   'clouds_low': 31,
   'clouds_mid': 0,
   'datetime': '2026-01-03:00',
   'dewpt': 5.5,
   'dhi': 0,
   'dni': 0,
   'ghi': 0,
   'ozone': 257,
   'pod': 'n',
   'pop': 0,
   'precip': 0,
   'pres': 919,
   'rh': 93,
   'slp': 1019,
   'snow': 0,
   'snow_depth': 0,
   'solar_rad': 0,
   'temp': 6.5,
   'timestamp_local': '2026-01-03T05:45:00',
   'timestamp_utc': '2026-01-03T00:00:00',
   'ts': 1767398400,
   'uv': 0,
   'vis': 24,
   'weather': {'icon': 'c01n', 'code': 800, 'description': 'Clear Sky'},
   'wind_cdir': 'NW',
   'wind_cdir_full': 'northwest',
   'wind_dir': 323,
   'wind_gust_spd': 2.69,
   'wind_spd': 1.54},
  {'app_temp': 5.4,
   'clouds': 0,
   'clouds_hi': 0,
   'clouds_low': 41,
   'clouds_mid': 0,
   'datetime': '2026-01-03:01',
   'dewpt': 5.4,
   'dhi': 0,
   'dni': 0,
   'ghi': 0,
   'ozone': 258,
   'pod': 'n',
   'pop': 0,
   'precip': 0,
   'pres': 919,
   'rh': 94,
   'slp': 1019,
   'snow': 0,
   'snow_depth': 0,
   'solar_rad': 0,
   'temp': 6.3,
   'timestamp_local': '2026-01-03T06:45:00',
   'timestamp_utc': '2026-01-03T01:00:00',
   'ts': 1767402000,
   'uv': 0,
   'vis': 24,
   'weather': {'icon': 'c01n', 'code': 800, 'description': 'Clear Sky'},
   'wind_cdir': 'NNW',
   'wind_cdir_full': 'north-northwest',
   'wind_dir': 329,
   'wind_gust_spd': 2.67,
   'wind_spd': 1.51},
  {'app_temp': 5.8,
   'clouds': 0,
   'clouds_hi': 0,
   'clouds_low': 56,
   'clouds_mid': 0,
   'datetime': '2026-01-03:02',
   'dewpt': 5.7,
   'dhi': 46,
   'dni': 428,
   'ghi': 94,
   'ozone': 256,
   'pod': 'd',
   'pop': 0,
   'precip': 0,
   'pres': 920,
   'rh': 94,
   'slp': 1020,
   'snow': 0,
   'snow_depth': 0,
   'solar_rad': 94.17,
   'temp': 6.6,
   'timestamp_local': '2026-01-03T07:45:00',
   'timestamp_utc': '2026-01-03T02:00:00',
   'ts': 1767405600,
   'uv': 2,
   'vis': 24,
   'weather': {'icon': 'c01d', 'code': 800, 'description': 'Clear Sky'},
   'wind_cdir': 'NNW',
   'wind_cdir_full': 'north-northwest',
   'wind_dir': 332,
   'wind_gust_spd': 2.61,
   'wind_spd': 1.48},
  {'app_temp': 9.6,
   'clouds': 0,
   'clouds_hi': 0,
   'clouds_low': 59,
   'clouds_mid': 0,
   'datetime': '2026-01-03:03',
   'dewpt': 8.4,
   'dhi': 76,
   'dni': 684,
   'ghi': 284,
   'ozone': 256,
   'pod': 'd',
   'pop': 0,
   'precip': 0,
   'pres': 921,
   'rh': 92,
   'slp': 1020,
   'snow': 0,
   'snow_depth': 0,
   'solar_rad': 284.5,
   'temp': 9.6,
   'timestamp_local': '2026-01-03T08:45:00',
   'timestamp_utc': '2026-01-03T03:00:00',
   'ts': 1767409200,
   'uv': 2,
   'vis': 24,
   'weather': {'icon': 'c01d', 'code': 800, 'description': 'Clear Sky'},
   'wind_cdir': 'NNW',
   'wind_cdir_full': 'north-northwest',
   'wind_dir': 337,
   'wind_gust_spd': 2.54,
   'wind_spd': 0.86},
  {'app_temp': 13.1,
   'clouds': 0,
   'clouds_hi': 0,
   'clouds_low': 52,
   'clouds_mid': 0,
   'datetime': '2026-01-03:04',
   'dewpt': 9,
   'dhi': 92,
   'dni': 798,
   'ghi': 456,
   'ozone': 255,
   'pod': 'd',
   'pop': 0,
   'precip': 0,
   'pres': 922,
   'rh': 76,
   'slp': 1020,
   'snow': 0,
   'snow_depth': 0,
   'solar_rad': 456.39,
   'temp': 13.1,
   'timestamp_local': '2026-01-03T09:45:00',
   'timestamp_utc': '2026-01-03T04:00:00',
   'ts': 1767412800,
   'uv': 3,
   'vis': 24,
   'weather': {'icon': 'c01d', 'code': 800, 'description': 'Clear Sky'},
   'wind_cdir': 'E',
   'wind_cdir_full': 'east',
   'wind_dir': 95,
   'wind_gust_spd': 1.71,
   'wind_spd': 0.32},
  {'app_temp': 14.8,
   'clouds': 0,
   'clouds_hi': 0,
   'clouds_low': 35,
   'clouds_mid': 0,
   'datetime': '2026-01-03:05',
   'dewpt': 10.2,
   'dhi': 102,
   'dni': 856,
   'ghi': 582,
   'ozone': 256,
   'pod': 'd',
   'pop': 0,
   'precip': 0,
   'pres': 922,
   'rh': 74,
   'slp': 1020,
   'snow': 0,
   'snow_depth': 0,
   'solar_rad': 564.7968,
   'temp': 14.8,
   'timestamp_local': '2026-01-03T10:45:00',
   'timestamp_utc': '2026-01-03T05:00:00',
   'ts': 1767416400,
   'uv': 4,
   'vis': 24,
   'weather': {'icon': 'c01d', 'code': 800, 'description': 'Clear Sky'},
   'wind_cdir': 'SE',
   'wind_cdir_full': 'southeast',
   'wind_dir': 134,
   'wind_gust_spd': 2.54,
   'wind_spd': 0.89},
  {'app_temp': 15.9,
   'clouds': 0,
   'clouds_hi': 0,
   'clouds_low': 47,
   'clouds_mid': 0,
   'datetime': '2026-01-03:06',
   'dewpt': 10,
   'dhi': 106,
   'dni': 881,
   'ghi': 648,
   'ozone': 255,
   'pod': 'd',
   'pop': 0,
   'precip': 0,
   'pres': 921,
   'rh': 68,
   'slp': 1018,
   'snow': 0,
   'snow_depth': 0,
   'solar_rad': 647.89,
   'temp': 15.9,
   'timestamp_local': '2026-01-03T11:45:00',
   'timestamp_utc': '2026-01-03T06:00:00',
   'ts': 1767420000,
   'uv': 5,
   'vis': 24,
   'weather': {'icon': 'c01d', 'code': 800, 'description': 'Clear Sky'},
   'wind_cdir': 'SE',
   'wind_cdir_full': 'southeast',
   'wind_dir': 138,
   'wind_gust_spd': 3.27,
   'wind_spd': 1.33},
  {'app_temp': 16.6,
   'clouds': 0,
   'clouds_hi': 0,
   'clouds_low': 43,
   'clouds_mid': 0,
   'datetime': '2026-01-03:07',
   'dewpt': 9.3,
   'dhi': 106,
   'dni': 880,
   'ghi': 646,
   'ozone': 254,
   'pod': 'd',
   'pop': 0,
   'precip': 0,
   'pres': 920,
   'rh': 62,
   'slp': 1017,
   'snow': 0,
   'snow_depth': 0,
   'solar_rad': 645.92,
   'temp': 16.6,
   'timestamp_local': '2026-01-03T12:45:00',
   'timestamp_utc': '2026-01-03T07:00:00',
   'ts': 1767423600,
   'uv': 4,
   'vis': 24,
   'weather': {'icon': 'c01d', 'code': 800, 'description': 'Clear Sky'},
   'wind_cdir': 'SE',
   'wind_cdir_full': 'southeast',
   'wind_dir': 143,
   'wind_gust_spd': 3.99,
   'wind_spd': 1.8},
  {'app_temp': 17.1,
   'clouds': 0,
   'clouds_hi': 0,
   'clouds_low': 42,
   'clouds_mid': 0,
   'datetime': '2026-01-03:08',
   'dewpt': 9,
   'dhi': 101,
   'dni': 854,
   'ghi': 577,
   'ozone': 254,
   'pod': 'd',
   'pop': 0,
   'precip': 0,
   'pres': 919,
   'rh': 59,
   'slp': 1017,
   'snow': 0,
   'snow_depth': 0,
   'solar_rad': 576.71,
   'temp': 17.1,
   'timestamp_local': '2026-01-03T13:45:00',
   'timestamp_utc': '2026-01-03T08:00:00',
   'ts': 1767427200,
   'uv': 4,
   'vis': 24,
   'weather': {'icon': 'c01d', 'code': 800, 'description': 'Clear Sky'},
   'wind_cdir': 'SSE',
   'wind_cdir_full': 'south-southeast',
   'wind_dir': 149,
   'wind_gust_spd': 4.65,
   'wind_spd': 2.3},
  {'app_temp': 16.9,
   'clouds': 0,
   'clouds_hi': 0,
   'clouds_low': 41,
   'clouds_mid': 0,
   'datetime': '2026-01-03:09',
   'dewpt': 8.6,
   'dhi': 91,
   'dni': 793,
   'ghi': 448,
   'ozone': 254,
   'pod': 'd',
   'pop': 0,
   'precip': 0,
   'pres': 919,
   'rh': 58,
   'slp': 1016,
   'snow': 0,
   'snow_depth': 0,
   'solar_rad': 447.55,
   'temp': 16.9,
   'timestamp_local': '2026-01-03T14:45:00',
   'timestamp_utc': '2026-01-03T09:00:00',
   'ts': 1767430800,
   'uv': 3,
   'vis': 24,
   'weather': {'icon': 'c01d', 'code': 800, 'description': 'Clear Sky'},
   'wind_cdir': 'SSE',
   'wind_cdir_full': 'south-southeast',
   'wind_dir': 154,
   'wind_gust_spd': 4.82,
   'wind_spd': 2.45},
  {'app_temp': 16.3,
   'clouds': 0,
   'clouds_hi': 0,
   'clouds_low': 41,
   'clouds_mid': 0,
   'datetime': '2026-01-03:10',
   'dewpt': 8.5,
   'dhi': 74,
   'dni': 675,
   'ghi': 274,
   'ozone': 254,
   'pod': 'd',
   'pop': 0,
   'precip': 0,
   'pres': 919,
   'rh': 60,
   'slp': 1016,
   'snow': 0,
   'snow_depth': 0,
   'solar_rad': 273.66,
   'temp': 16.3,
   'timestamp_local': '2026-01-03T15:45:00',
   'timestamp_utc': '2026-01-03T10:00:00',
   'ts': 1767434400,
   'uv': 2,
   'vis': 24,
   'weather': {'icon': 'c01d', 'code': 800, 'description': 'Clear Sky'},
   'wind_cdir': 'SSE',
   'wind_cdir_full': 'south-southeast',
   'wind_dir': 163,
   'wind_gust_spd': 4.66,
   'wind_spd': 2.32},
  {'app_temp': 15.3,
   'clouds': 0,
   'clouds_hi': 0,
   'clouds_low': 44,
   'clouds_mid': 33,
   'datetime': '2026-01-03:11',
   'dewpt': 8.5,
   'dhi': 44,
   'dni': 403,
   'ghi': 84,
   'ozone': 254,
   'pod': 'd',
   'pop': 0,
   'precip': 0,
   'pres': 919,
   'rh': 64,
   'slp': 1016,
   'snow': 0,
   'snow_depth': 0,
   'solar_rad': 83.74,
   'temp': 15.3,
   'timestamp_local': '2026-01-03T16:45:00',
   'timestamp_utc': '2026-01-03T11:00:00',
   'ts': 1767438000,
   'uv': 2,
   'vis': 24,
   'weather': {'icon': 'c01d', 'code': 800, 'description': 'Clear Sky'},
   'wind_cdir': 'SSE',
   'wind_cdir_full': 'south-southeast',
   'wind_dir': 161,
   'wind_gust_spd': 4.35,
   'wind_spd': 1.75},
  {'app_temp': 13.5,
   'clouds': 0,
   'clouds_hi': 0,
   'clouds_low': 29,
   'clouds_mid': 47,
   'datetime': '2026-01-03:12',
   'dewpt': 9,
   'dhi': 0,
   'dni': 0,
   'ghi': 0,
   'ozone': 253,
   'pod': 'n',
   'pop': 0,
   'precip': 0,
   'pres': 919,
   'rh': 74,
   'slp': 1017,
   'snow': 0,
   'snow_depth': 0,
   'solar_rad': 0,
   'temp': 13.5,
   'timestamp_local': '2026-01-03T17:45:00',
   'timestamp_utc': '2026-01-03T12:00:00',
   'ts': 1767441600,
   'uv': 0,
   'vis': 24,
   'weather': {'icon': 'c01n', 'code': 800, 'description': 'Clear Sky'},
   'wind_cdir': 'SE',
   'wind_cdir_full': 'southeast',
   'wind_dir': 146,
   'wind_gust_spd': 3.22,
   'wind_spd': 1.42},
  {'app_temp': 12,
   'clouds': 0,
   'clouds_hi': 0,
   'clouds_low': 26,
   'clouds_mid': 34,
   'datetime': '2026-01-03:13',
   'dewpt': 9.4,
   'dhi': 0,
   'dni': 0,
   'ghi': 0,
   'ozone': 254,
   'pod': 'n',
   'pop': 0,
   'precip': 0,
   'pres': 920,
   'rh': 84,
   'slp': 1018,
   'snow': 0,
   'snow_depth': 0,
   'solar_rad': 0,
   'temp': 12,
   'timestamp_local': '2026-01-03T18:45:00',
   'timestamp_utc': '2026-01-03T13:00:00',
   'ts': 1767445200,
   'uv': 0,
   'vis': 24,
   'weather': {'icon': 'c01n', 'code': 800, 'description': 'Clear Sky'},
   'wind_cdir': 'SE',
   'wind_cdir_full': 'southeast',
   'wind_dir': 146,
   'wind_gust_spd': 2.46,
   'wind_spd': 0.97},
  {'app_temp': 11.2,
   'clouds': 0,
   'clouds_hi': 0,
   'clouds_low': 31,
   'clouds_mid': 33,
   'datetime': '2026-01-03:14',
   'dewpt': 9.3,
   'dhi': 0,
   'dni': 0,
   'ghi': 0,
   'ozone': 253,
   'pod': 'n',
   'pop': 0,
   'precip': 0,
   'pres': 920,
   'rh': 88,
   'slp': 1018,
   'snow': 0,
   'snow_depth': 0,
   'solar_rad': 0,
   'temp': 11.2,

In [11]:
df = pd.DataFrame(response.json())

In [12]:
df

,city_name,country_code,data,lat,lon,state_code,timezone
0,Bhattarai Danda,NP,"{'app_temp': 16.4, 'clouds': 0, 'clouds_hi': 0...",28,84,WR,Asia/Kathmandu
1,Bhattarai Danda,NP,"{'app_temp': 15.4, 'clouds': 0, 'clouds_hi': 0...",28,84,WR,Asia/Kathmandu
2,Bhattarai Danda,NP,"{'app_temp': 13.7, 'clouds': 0, 'clouds_hi': 0...",28,84,WR,Asia/Kathmandu
3,Bhattarai Danda,NP,"{'app_temp': 12.1, 'clouds': 0, 'clouds_hi': 0...",28,84,WR,Asia/Kathmandu
4,Bhattarai Danda,NP,"{'app_temp': 11.4, 'clouds': 0, 'clouds_hi': 0...",28,84,WR,Asia/Kathmandu
...,...,...,...,...,...,...,...
116,Bhattarai Danda,NP,"{'app_temp': 17.9, 'clouds': 0, 'clouds_hi': 0...",28,84,WR,Asia/Kathmandu
117,Bhattarai Danda,NP,"{'app_temp': 18.3, 'clouds': 0, 'clouds_hi': 0...",28,84,WR,Asia/Kathmandu
118,Bhattarai Danda,NP,"{'app_temp': 17.3, 'clouds': 0, 'clouds_hi': 0...",28,84,WR,Asia/Kathmandu
119,Bhattarai Danda,NP,"{'app_temp': 17.6, 'clouds': 0, 'clouds_hi': 0...",28,84,WR,Asia/Kathmandu
120,Bhattarai Danda,NP,"{'app_temp': 16.5, 'clouds': 0, 'clouds_hi': 0...",28,84,WR,Asia/Kathmandu

In [18]:
df['weather_description'] = df['data'][1]['weather']['description']
df['timestamp_local'] = df['data'][1]['timestamp_local']
df['timestamp_utc'] = df['data'][1]['timestamp_utc']
df['datetime'] = df['data'][1]['datetime']

In [22]:
df.drop(columns={"data"},inplace=True)

In [25]:
df

,city_name,country_code,lat,lon,state_code,timezone,weather_description,timestamp_local,timestamp_utc,datetime
0,Bhattarai Danda,NP,28,84,WR,Asia/Kathmandu,Clear Sky,2026-01-02T16:45:00,2026-01-02T11:00:00,2026-01-02:11
1,Bhattarai Danda,NP,28,84,WR,Asia/Kathmandu,Clear Sky,2026-01-02T16:45:00,2026-01-02T11:00:00,2026-01-02:11
2,Bhattarai Danda,NP,28,84,WR,Asia/Kathmandu,Clear Sky,2026-01-02T16:45:00,2026-01-02T11:00:00,2026-01-02:11
3,Bhattarai Danda,NP,28,84,WR,Asia/Kathmandu,Clear Sky,2026-01-02T16:45:00,2026-01-02T11:00:00,2026-01-02:11
4,Bhattarai Danda,NP,28,84,WR,Asia/Kathmandu,Clear Sky,2026-01-02T16:45:00,2026-01-02T11:00:00,2026-01-02:11
...,...,...,...,...,...,...,...,...,...,...
116,Bhattarai Danda,NP,28,84,WR,Asia/Kathmandu,Clear Sky,2026-01-02T16:45:00,2026-01-02T11:00:00,2026-01-02:11
117,Bhattarai Danda,NP,28,84,WR,Asia/Kathmandu,Clear Sky,2026-01-02T16:45:00,2026-01-02T11:00:00,2026-01-02:11
118,Bhattarai Danda,NP,28,84,WR,Asia/Kathmandu,Clear Sky,2026-01-02T16:45:00,2026-01-02T11:00:00,2026-01-02:11
119,Bhattarai Danda,NP,28,84,WR,Asia/Kathmandu,Clear Sky,2026-01-02T16:45:00,2026-01-02T11:00:00,2026-01-02:11
120,Bhattarai Danda,NP,28,84,WR,Asia/Kathmandu,Clear Sky,2026-01-02T16:45:00,2026-01-02T11:00:00,2026-01-02:11