In [9]:
import os

In [8]:
TMDB_API_ACCESS_TOKEN = os.getenv("TMDB_API_ACCESS_TOKEN")

In [ ]:
import requests

url = "https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=1"

headers = {
            "accept": "application/json",
           'Authorization': f"Bearer {TMDB_API_ACCESS_TOKEN}"
}

response = requests.get(url, headers=headers)

if response.status_code == 200:
    print(response.json())

{'page': 1, 'results': [{'adult': False, 'backdrop_path': '/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg', 'genre_ids': [18, 80], 'id': 278, 'original_language': 'en', 'original_title': 'The Shawshank Redemption', 'overview': 'Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.', 'popularity': 45.9678, 'poster_path': '/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg', 'release_date': '1994-09-23', 'title': 'The Shawshank Redemption', 'video': False, 'vote_average': 8.713, 'vote_count': 29430}, {'adult': False, 'backdrop_path': '/39rtAdg3yx6IDxRg0ZLXefv0aPY.jpg', 'genre_ids': [18, 80], 'id': 238, 'original_language': 'en', 'original_title': 'The Godfather', 'overview': 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.', 'popularity': 35.303, 'poster_path': '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg', 'release_date': '1972-03-14', 'title': 'The Godfather', 'video': False, 'vote_average': 8.685, 'vote_count': 22214}, {'adult': False, 'backdrop_path': '/14icRpwdgpHEHxt7Cn5hr2RQEsF.jpg', 'genre_ids': [18, 80], 'id': 240, 'original_language': 'en', 'original_title': 'The Godfather Part II', 'overview': 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.', 'popularity': 19.4904, 'poster_path': '/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg', 'release_date': '1974-12-20', 'title': 'The Godfather Part II', 'video': False, 'vote_average': 8.571, 'vote_count': 13434}, {'adult': False, 'backdrop_path': '/zb6fM1CX41D9rF9hdgclu0peUmy.jpg', 'genre_ids': [18, 36, 10752], 'id': 424, 'original_language': 'en', 'original_title': "Schindler's List", 'overview': 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.', 'popularity': 16.4358, 'poster_path': '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg', 'release_date': '1993-12-15', 'title': "Schindler's List", 'video': False, 'vote_average': 8.565, 'vote_count': 16946}, {'adult': False, 'backdrop_path': '/w4bTBXcqXc2TUyS5Fc4h67uWbPn.jpg', 'genre_ids': [18], 'id': 389, 'original_language': 'en', 'original_title': '12 Angry Men', 'overview': "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.", 'popularity': 12.4809, 'poster_path': '/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg', 'release_date': '1957-04-10', 'title': '12 Angry Men', 'video': False, 'vote_average': 8.549, 'vote_count': 9617}, {'adult': False, 'backdrop_path': '/ukfI9QkU1aIhOhKXYWE9n3z1mFR.jpg', 'genre_ids': [16, 10751, 14], 'id': 129, 'original_language': 'ja', 'original_title': '千と千尋の神隠し', 'overview': 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.', 'popularity': 23.1737, 'poster_path': '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg', 'release_date': '2001-07-20', 'title': 'Spirited Away', 'video': False, 'vote_average': 8.533, 'vote_count': 17760}, {'adult': False, 'backdrop_path': '/dGOZdWOB8OpZFVziEOUFhox5wz9.jpg', 'genre_ids': [18, 28, 80, 53], 'id': 155, 'original_language': 'en', 'original_title': 'The Dark Knight', 'overview': 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.', 'popularity': 27.8207, 'poster_path': '/qJ2tW6WMUDux911r6m7haRef0WH.jpg', 'release_date': '2008-07-16', 'title': 'The Dark Knight', 'video': False, 'vote_average': 8.525, 'vote_count': 34908}, {'adult': False, 'backdrop_path': '/zQDFHYNVVVp9OAYSixYAG1SyX1l.jpg', 'genre_ids': [35, 18, 10749], 'id': 19404, 'original_language': 'hi', 'original_title': 'दिलवाले दुल्हनिया ले जायेंगे', 'overview': 'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.', 'popularity': 7.5818, 'poster_path': '/2CAL2433ZeIihfX1Hb2139CX0pW.jpg', 'release_date': '1995-10-20', 'title': 'Dilwale Dulhania Le Jayenge', 'video': False, 'vote_average': 8.516, 'vote_count': 4533}, {'adult': False, 'backdrop_path': '/b6HWTOxn1xevvyHU2K9ICvaRU6g.jpg', 'genre_ids': [14, 18, 80], 'id': 497, 'original_language': 'en', 'original_title': 'The Green Mile', 'overview': "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.", 'popularity': 21.5143, 'poster_path': '/o0lO84GI7qrG6XFvtsPOSV7CTNa.jpg', 'release_date': '1999-12-10', 'title': 'The Green Mile', 'video': False, 'vote_average': 8.503, 'vote_count': 18665}, {'adult': False, 'backdrop_path': '/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg', 'genre_ids': [35, 53, 18], 'id': 496243, 'original_language': 'ko', 'original_title': '기생충', 'overview': "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.", 'popularity': 25.9749, 'poster_path': '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg', 'release_date': '2019-05-30', 'title': 'Parasite', 'video': False, 'vote_average': 8.495, 'vote_count': 19872}, {'adult': False, 'backdrop_path': '/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg', 'genre_ids': [12, 14, 28], 'id': 122, 'original_language': 'en', 'original_title': 'The Lord of the Rings: The Return of the King', 'overview': 'As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.\u200b', 'popularity': 30.6808, 'poster_path': '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg', 'release_date': '2003-12-17', 'title': 'The Lord of the Rings: The Return of the King', 'video': False, 'vote_average': 8.492, 'vote_count': 25796}, {'adult': False, 'backdrop_path': '/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg', 'genre_ids': [53, 80, 35], 'id': 680, 'original_language': 'en', 'original_title': 'Pulp Fiction', 'overview': "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.", 'popularity': 24.7222, 'poster_path': '/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg', 'release_date': '1994-09-10', 'title': 'Pulp Fiction', 'video': False, 'vote_average': 8.486, 'vote_count': 29451}, {'adult': False, 'backdrop_path': '/8x9iKH8kWA0zdkgNdpAew7OstYe.jpg', 'genre_ids': [16, 10749, 18], 'id': 372058, 'original_language': 'ja', 'original_title': '君の名は。', 'overview': 'High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.', 'popularity': 22.9329, 'poster_path': '/q719jXXEzOoYaps6babgKnONONX.jpg', 'release_date': '2016-08-26', 'title': 'Your Name.', 'video': False, 'vote_average': 8.48, 'vote_count': 12186}, {'adult': False, 'backdrop_path': '/Adrip2Jqzw56KeuV2nAxucKMNXA.jpg', 'genre_ids': [37], 'id': 429, 'original_language': 'it', 'original_title': 'Il buono, il brutto, il cattivo', 'overview': 'While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.', 'popularity': 14.1832, 'poster_path': '/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg', 'release_date': '1966-12-22', 'title': 'The Good, the Bad and the Ugly', 'video': False, 'vote_average': 8.467, 'vote_count': 9310}, {'adult': False, 'backdrop_path': '/5XNQBqnBwPA9yT0jZ0p3s8bbLh0.jpg', 'genre_ids': [12, 18, 878], 'id': 157336, 'original_language': 'en', 'original_title': 'Interstellar', 'overview': 'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.', 'popularity': 40.6451, 'poster_path': '/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg', 'release_date': '2014-11-05', 'title': 'Interstellar', 'video': False, 'vote_average': 8.5, 'vote_count': 38492}, {'adult': False, 'backdrop_path': '/67HggiWaP9ZLv5sPYmyRV37yAJM.jpg', 'genre_ids': [35, 18, 10749], 'id': 13, 'original_language': 'en', 'original_title': 'Forrest Gump', 'overview': 'A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.', 'popularity': 23.841, 'poster_path': '/saHP97rTPS5eLmrLQEcANmKrsFl.jpg', 'release_date': '1994-06-23', 'title': 'Forrest Gump', 'video': False, 'vote_average': 8.462, 'vote_count': 29029}, {'adult': False, 'backdrop_path': '/7TF4p86ZafnxFuNqWdhpHXFO244.jpg', 'genre_ids': [18, 80], 'id': 769, 'original_language': 'en', 'original_title': 'GoodFellas', 'overview': 'The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.', 'popularity': 18.8334, 'poster_path': '/9OkCLM73MIU2CrKZbqiT8Ln1wY2.jpg', 'release_date': '1990-09-12', 'title': 'GoodFellas', 'video': False, 'vote_average': 8.452, 'vote_count': 13872}, {'adult': False, 'backdrop_path': '/qvZ91FwMq6O47VViAr8vZNQz3WI.jpg', 'genre_ids': [28, 18], 'id': 346, 'original_language': 'ja', 'original_title': '七人の侍', 'overview': "A samurai answers a village's request for protection after he falls on hard times. The town needs protection from bandits, so the samurai gathers six others to help him teach the people how to defend themselves, and the villagers provide the soldiers with food.", 'popularity': 10.7777, 'poster_path': '/lOMGc8bnSwQhS4XyE1S99uH8NXf.jpg', 'release_date': '1954-04-26', 'title': 'Seven Samurai', 'video': False, 'vote_average': 8.452, 'vote_count': 4063}, {'adult': False, 'backdrop_path': '/aHaqZpOL7UyVu0nKqp3SMz0o2E1.jpg', 'genre_ids': [16, 18, 10752], 'id': 12477, 'original_language': 'ja', 'original_title': '火垂るの墓', 'overview': 'In the final months of World War II, 14-year-old Seita and his sister Setsuko are orphaned when their mother is killed during an air raid in Kobe, Japan. After a falling out with their aunt, they move into an abandoned bomb shelter. With no surviving relatives and their emergency rations depleted, Seita and Setsuko struggle to survive.', 'popularity': 0.0112, 'poster_path': '/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg', 'release_date': '1988-04-16', 'title': 'Grave of the Fireflies', 'video': False, 'vote_average': 8.446, 'vote_count': 6252}, {'adult': False, 'backdrop_path': '/6aNKD81RHR1DqUUa8kOZ1TBY1Lp.jpg', 'genre_ids': [35, 18], 'id': 637, 'original_language': 'it', 'original_title': 'La vita è bella', 'overview': 'A touching story of an Italian book seller of Jewish ancestry who lives in his own little fairy tale. His creative and happy life would come to an abrupt halt when his entire family is deported to a concentration camp during World War II. While locked up he tries to convince his son that the whole thing is just a game.', 'popularity': 7.9137, 'poster_path': '/mfnkSeeVOBVheuyn2lo4tfmOPQb.jpg', 'release_date': '1997-12-20', 'title': 'Life Is Beautiful', 'video': False, 'vote_average': 8.441, 'vote_count': 13693}], 'total_pages': 528, 'total_results': 10560}

In [13]:
import pandas as pd

In [18]:
df = pd.DataFrame(response.json()['results'])

In [19]:
df.head()

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg,"[18, 80]",278,en,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,45.9678,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,1994-09-23,The Shawshank Redemption,False,8.713,29430
1,False,/39rtAdg3yx6IDxRg0ZLXefv0aPY.jpg,"[18, 80]",238,en,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",35.3030,/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,1972-03-14,The Godfather,False,8.685,22214
2,False,/14icRpwdgpHEHxt7Cn5hr2RQEsF.jpg,"[18, 80]",240,en,The Godfather Part II,In the continuing saga of the Corleone crime f...,19.4904,/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg,1974-12-20,The Godfather Part II,False,8.571,13434
3,False,/zb6fM1CX41D9rF9hdgclu0peUmy.jpg,"[18, 36, 10752]",424,en,Schindler's List,The true story of how businessman Oskar Schind...,16.4358,/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg,1993-12-15,Schindler's List,False,8.565,16946
4,False,/w4bTBXcqXc2TUyS5Fc4h67uWbPn.jpg,[18],389,en,12 Angry Men,The defense and the prosecution have rested an...,12.4809,/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg,1957-04-10,12 Angry Men,False,8.549,9617

In [20]:
df = df[['id', 'title', 'overview','release_date', 'popularity', 'vote_average', 'vote_count']]

In [ ]:
df.shape # 1 paage, 20 movies

(20, 7)

In [32]:
# now we will do that in loop for all pages

df = pd.DataFrame()

for i in range(1, 429):
    url = f"https://api.themoviedb.org/3/movie/top_rated?language=en-US&page={i}"

    headers = {
            "accept": "application/json",
           'Authorization': f"Bearer {TMDB_API_ACCESS_TOKEN}"
    }

    response = requests.get(url, headers=headers)
    df= pd.concat([df, pd.DataFrame(response.json()['results'])[['id', 'title', 'overview','release_date', 'popularity', 'vote_average', 'vote_count']]])

In [37]:
df.reset_index(drop=True, inplace=True)

In [ ]:
# same code but only 1 time fetching from the server => 2.3s compared to 4m 28s in the above code

df = pd.DataFrame()

url = f"https://api.themoviedb.org/3/movie/top_rated"
headers = {
            "accept": "application/json",
           'Authorization': f"Bearer {TMDB_API_ACCESS_TOKEN}"
    }
response = requests.get(url, headers=headers)

for i in range(1, response.json()['total_pages'] + 1):

    df= pd.concat([df, pd.DataFrame(response.json()['results'])[['id', 'title', 'overview','release_date', 'popularity', 'vote_average', 'vote_count']]], ignore_index=True)

In [44]:
df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,45.9678,8.713,29430
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,35.3030,8.685,22214
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,19.4904,8.571,13434
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,16.4358,8.565,16946
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,12.4809,8.549,9617
...,...,...,...,...,...,...,...
10555,13,Forrest Gump,A man with a low IQ has accomplished great thi...,1994-06-23,23.8410,8.462,29029
10556,769,GoodFellas,"The true story of Henry Hill, a half-Irish, ha...",1990-09-12,18.8334,8.452,13872
10557,346,Seven Samurai,A samurai answers a village's request for prot...,1954-04-26,10.7777,8.452,4063
10558,12477,Grave of the Fireflies,"In the final months of World War II, 14-year-o...",1988-04-16,0.0112,8.446,6252
10559,637,Life Is Beautiful,A touching story of an Italian book seller of ...,1997-12-20,7.9137,8.441,13693