In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.compose import ColumnTransformer

In [2]:
df = pd.read_csv("Titanic-Dataset.csv")

In [4]:
df.drop(columns=['PassengerId', 'Name','Ticket', "Cabin"], inplace=True)

In [5]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [6]:
ohe = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

In [24]:
encoded = ohe.fit_transform(df[["Sex", "Embarked"]])

In [25]:
ohe.get_feature_names_out()

array(['Sex_female', 'Sex_male', 'Embarked_C', 'Embarked_Q', 'Embarked_S',
       'Embarked_nan'], dtype=object)

In [27]:
encoded_df = pd.DataFrame(
    encoded,
    columns=ohe.get_feature_names_out(["Sex", "Embarked"])
)

In [28]:
encoded_df

     Sex_female  Sex_male  Embarked_C  Embarked_Q  Embarked_S  Embarked_nan
0           0.0       1.0         0.0         0.0         1.0           0.0
1           1.0       0.0         1.0         0.0         0.0           0.0
2           1.0       0.0         0.0         0.0         1.0           0.0
3           1.0       0.0         0.0         0.0         1.0           0.0
4           0.0       1.0         0.0         0.0         1.0           0.0
..          ...       ...         ...         ...         ...           ...
886         0.0       1.0         0.0         0.0         1.0           0.0
887         1.0       0.0         0.0         0.0         1.0           0.0
888         1.0       0.0         0.0         0.0         1.0           0.0
889         0.0       1.0         1.0         0.0         0.0           0.0
890         0.0       1.0         0.0         1.0         0.0           0.0

[891 rows x 6 columns]