In [1]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv("spam.csv", encoding='latin1')

In [4]:
# To detect encoding type in any file
%pip install chardet

Requirement already satisfied: chardet in /home/sakshi-khatiwada/Desktop/My Repos/Python/.venv/lib/python3.12/site-packages (5.2.0)
Note: you may need to restart the kernel to use updated packages.

In [6]:
import chardet
with open('spam.csv', 'rb') as f: #IMP open in binary-mode
    text = f.read(5000)

encoding = chardet.detect(text)
print("encoder result: ", encoding)

encoder result:  {'encoding': 'Windows-1252', 'confidence': 0.7197765921973991, 'language': ''}

In [13]:
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [15]:
df.shape

(5572, 5)

Steps We will be Performing:
> Data Cleaning  
> Exploratory Data Analysis (EDA)  
> Text Preprocessing  
> Model Building  
> Evaluation  
> Improvement  
> Website  
> Deploy

## 1. Data Cleaning
Includes:  
Dropping Unnecessary Columns,  
Renaming the columns if necessary,  
Encoding the target variable,  
Checking for missing values or duplicate values and act accordingly

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   v1          5572 non-null   object
 1   v2          5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB

In [23]:
df.drop(columns=['Unnamed: 2','Unnamed: 3', 'Unnamed: 4'], inplace=True) #IMP - I almost forgot inplace

In [24]:
df.rename(columns={'v1': 'target', 'v2': 'text'}, inplace=True)

In [26]:
df.sample(5)

     target                                               text
3783    ham            Dear got train and seat mine lower seat
2977    ham  Yar lor... Keep raining non stop... Or u wan 2...
2935    ham  And stop wondering \wow is she ever going to s...
4596    ham             Full heat pa:-) i have applyed oil pa.
191     ham  I'm sorry. I've joined the league of people th...

In [28]:
from sklearn.preprocessing import LabelEncoder

In [29]:
encoder = LabelEncoder()

df['target'] = encoder.fit_transform(df['target'])
df.head()

   target                                               text
0       0  Go until jurong point, crazy.. Available only ...
1       0                      Ok lar... Joking wif u oni...
2       1  Free entry in 2 a wkly comp to win FA Cup fina...
3       0  U dun say so early hor... U c already then say...
4       0  Nah I don't think he goes to usf, he lives aro...

In [30]:
df.isna().sum()

target    0
text      0
dtype: int64

In [31]:
df.duplicated().sum()

np.int64(403)

In [32]:
df.drop_duplicates(keep='first', inplace=True)

In [33]:
df.duplicated().sum()

np.int64(0)

## 2. Exploratory Data Analysis (EDA)